aws:
  sqsWorkersInputQueueName: "WorkersInputQueue"
  sqsWorkersOutputQueueName: "WorkersOutputQueue"
  entityTypes:
    - PERSON
    - LOCATION
    - ORGANIZATION
  sarcasmThreshold: 2
  processingThreads: 2
  consumerVisibilityTimeout: 30
  consumerVisibilityThreadSleepTime: 10
  consumerMaxMessagesPerPoll: 5
  consumerMaxMessagesInFlight: 10
