aws:
  managerName: "Manager"
  bucketName: "assignment1-reviews"
  sqsTasksInputQueueName: "TasksInputQueue"
  sqsWorkersInputQueueName: "WorkersInputQueue"
  sqsWorkersOutputQueueName: "WorkersOutputQueue"
  workersKeepAliveQueueName: "WorkersKeepAliveQueue"
  minWorkersCount: 3
  maxWorkersCount: 8
  workersKeepAliveTimeoutSeconds: 60
  workersBootGracefulTime: 300
  workersReduceThreshold: 1
  workersHandlerThreadSleepTime: 30
  consumerThreads: 5
  consumerVisibilityTimeout: 30
  consumerVisibilityThreadSleepTime: 10
  ec2Name: "Worker"
  instanceType: "t4g.large"
  ami: "ami-0e4b9fe67ab21f3a7"
  instanceProfileName: "LabInstanceProfile"
  securityGroupName: "default"
  userDataCommands:
    - "#!/bin/bash"
    - "exec >> /tmp/log"
    - "exec 2>&1"
    - "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)"
    - "AWS_REGION=us-east-1"
    - "MODE=WORKER"
    - "systemctl start docker"
    - "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
    - "docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/assignments:latest"
    - "docker run --net host -d -e MODE=$MODE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/assignments:latest"
